"use client";

import React from "react";
import styles from "./TermsOfService.module.css";

export default function TermsOfService() {
  return (
    <article className={styles.container} aria-label="SuperUtility Terms of Service and Privacy Policy">
      <div className={styles.titleSection}>
        <h1 className={styles.mainTitle}>Terms & Privacy Policy</h1>
        <div className={styles.lastUpdated}>Last Updated: May 2026</div>
      </div>

      <div className={styles.card}>
        {/* Core Guarantee Badge */}
        <div className={styles.badge} id="privacy-guarantee-badge">
          <span className={styles.badgeDot}></span>
          <span>100% Client-Side Sandbox Guarantee</span>
        </div>

        {/* Section 1: Privacy Paradigm */}
        <section className={styles.section} aria-labelledby="privacy-paradigm-heading">
          <h2 className={styles.sectionTitle} id="privacy-paradigm-heading">
            <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" className={styles.sectionIcon}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z" />
            </svg>
            1. Zero-Data Privacy Policy
          </h2>
          <p className={styles.text}>
            SuperUtility has been engineered from the ground up to respect absolute data sovereignty. Unlike standard developer platforms that upload password hashes, generator ranges, or file streams to remote servers, <span className={styles.highlightText}>every single execution occurs on your local hardware</span>.
          </p>
          <ul className={styles.list}>
            <li className={styles.listItem}><strong>No Server Logs:</strong> We do not operate any database, API backend, or server queues. Your inputs never touch the cloud.</li>
            <li className={styles.listItem}><strong>No Tracking or Cookies:</strong> SuperUtility implements a strict sandbox policy. No analytics tags, cookies, or remote advertising scripts are embedded in the code.</li>
            <li className={styles.listItem}><strong>Offline Capability:</strong> Once loaded, you can sever your internet connection entirely, and the application will remain fully functional.</li>
          </ul>
        </section>

        {/* Section 2: Terms of Service */}
        <section className={styles.section} aria-labelledby="terms-heading">
          <h2 className={styles.sectionTitle} id="terms-heading">
            <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" className={styles.sectionIcon}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
            </svg>
            2. Terms of Use & Licensing
          </h2>
          <p className={styles.text}>
            By accessing SuperUtility, you agree to utilize its tools in compliance with local regulations. SuperUtility grants you a free, non-exclusive, worldwide, royalty-free license to use all tools for both personal and production/commercial needs:
          </p>
          <ul className={styles.list}>
            <li className={styles.listItem}><strong>Output Ownership:</strong> Any password, passphrase, vector QR graphic, bulk UUID dataset, hash checksum, or random selection generated by SuperUtility belongs 100% to you. We claim absolutely no ownership or intellectual copyright over outputs.</li>
            <li className={styles.listItem}><strong>Fair Use:</strong> You are free to compile, download, export, and embed outputs without attribution.</li>
          </ul>
        </section>

        {/* Section 3: Algorithm Disclaimers */}
        <section className={styles.section} aria-labelledby="disclaimer-heading">
          <h2 className={styles.sectionTitle} id="disclaimer-heading">
            <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24" className={styles.sectionIcon}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
            </svg>
            3. Cryptographic & Operational Disclaimers
          </h2>
          <p className={styles.text}>
            SuperUtility provides all developer utilities on an &quot;as is&quot; and &quot;as available&quot; basis, without warranties of any kind. 
          </p>
          <ul className={styles.list}>
            <li className={styles.listItem}><strong>Entropy Responsibility:</strong> While our password, number, and random picker generators utilize cryptographically secure client-side randomness pools (<code className={styles.seoCode}>window.crypto.getRandomValues</code>), the safety of generated keys depends on the security of your local operating system and browser environments.</li>
            <li className={styles.listItem}><strong>One-Way Hashing:</strong> MD5 and SHA-1 algorithms are provided strictly for file checksum comparisons and legacy validation. We recommend SHA-256 or SHA-512 for security-sensitive cryptographic hashing needs.</li>
          </ul>
        </section>
      </div>
    </article>
  );
}
